version: "3.9"

services:
  service-monitor:
    build: .
    container_name: service-monitor-app
    environment:
      # Por ahora, la app no usa DATABASE_URL, pero lo dejamos preparado y coherente
      - DATABASE_URL=sqlite:///./data/service_monitor.db
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8002:8000"
    volumes:
      # Carpeta 'data' del host -> /app/data del contenedor
      - ./data:/app/data
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: service-monitor-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: service-monitor-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
